import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { CartProvider } from "@/lib/cart-context";
import { DeliveryProvider } from "@/lib/delivery-context";
import { DeliveryLocationDialog } from "@/components/DeliveryLocationDialog";
import { WhatsAppFloat } from "@/components/Whatsappfloat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <Script
          src="https://js.paystack.co/v1/inline.js"
          strategy="beforeInteractive"
        />
      </head>

      <body className="min-h-full flex flex-col">
        <DeliveryProvider>
          <DeliveryLocationDialog />
          <WhatsAppFloat />
          <CartProvider>{children}</CartProvider>
        </DeliveryProvider>
      </body>
    </html>
  );
}
